name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  php-version:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
#          - "7.2"
#          - "7.3"
#          - "7.4"
#          - "8.0"
          - "8.1"
#          - "8.2"

    steps:
    - name: Install PHP
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "${{ matrix.php-version }}"
        coverage: "none"
        extensions: "yaml"
        ini-values: "zend.assertions=1"

    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php-version }}-v2-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php-version }}-v2-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Pre-flight checks
      run: |
        php bin/fileeye-mediaprobe --version
        # Remove the comment to the lines below during development, to let
        # re-compile the specification PHP file from the YAML files, and refresh
        # the media file dumps.
        php bin/fileeye-mediaprobe compile
        # php bin/fileeye-mediaprobe dump tests/media-samples tests/media-dumps

    - name: Run test suite
      run: vendor/bin/phpunit ./tests
#      run: vendor/bin/phpunit ./tests/NumberLongTest.php

    - name: Code style test
      if: ${{ matrix.php-version == 7.4 }}
      run: ./vendor/bin/phpcs --runtime-set ignore_warnings_on_exit 1
